/**
 * Mask/Label Export Script
 * Generated by QuIET (QuPath Image Export Toolkit)
 *
 * Exports label masks from project images using LabeledImageServer.
 * Mask type: GRAYSCALE_LABELS
 *
 * Parameters below can be modified before re-running.
 */

import qupath.lib.images.servers.LabeledImageServer
import qupath.lib.images.writers.ImageWriterTools
import qupath.lib.objects.classes.PathClass
import qupath.lib.regions.RegionRequest

// ========== CONFIGURATION (modify as needed) ==========
def maskType = "GRAYSCALE_LABELS"
def downsample = 32.0
def outputFormat = "png"
def outputDir = "/path/to/save/location"
def backgroundLabel = 0
def objectSource = "ANNOTATIONS"
def classifications = ["class1", "class2", "class3"]
// =======================================================
/**
Note before running script:
The classifications listed in the above config will all be written out to the same img file
If different annotations from the same image should be saved as separate files, set the outputDir 
to a different location so any previously written images are not overwritten
Order of classes in the classification list determines the grey value applied
This script has been modified from the original generated from the QUiet extension to skip any images 
that do not contain the classifications listed above.
*/
def project = getProject()
if (project == null) {
    println 'ERROR: No project is open'
    return
}

def outDir = new File(outputDir)
outDir.mkdirs()

def entries = project.getImageList()
println "Processing ${entries.size()} images..."

int succeeded = 0
int failed = 0

for (int i = 0; i < entries.size(); i++) {
    def entry = entries[i]
    def entryName = entry.getImageName()
    def imageData = entry.readImageData()
    def hierarchy = imageData.getHierarchy()
    def anno = hierarchy.getAnnotationObjects().findAll {it.getPathClass() == getPathClass(classifications[2])}
    if (anno.isEmpty()) {
       println "${entryName} does not have path class, skipping"
    } else {
        println "[${i + 1}/${entries.size()}] Processing: ${entryName}"

        def labelServer = null
        try {
            def builder = new LabeledImageServer.Builder(imageData)
            builder.backgroundLabel(backgroundLabel)
            builder.downsample(downsample)
    
            switch (objectSource) {
                case 'ANNOTATIONS': builder.useAnnotations(); break
                case 'DETECTIONS': builder.useDetections(); break
                case 'CELLS': builder.useCells(); break
            }
    
            switch (maskType) {
                case 'BINARY':
                    if (classifications.isEmpty()) {
                        builder.addUnclassifiedLabel(1)
                    } else {
                        classifications.each { builder.addLabel(PathClass.fromString(it), 1) }
                    }
                    break
                case 'GRAYSCALE_LABELS':
                    builder.grayscale(true)
                    classifications.eachWithIndex { cls, idx -> builder.addLabel(PathClass.fromString(cls), idx + 1) }
                    break
                case 'COLORED':
                    classifications.eachWithIndex { cls, idx -> builder.addLabel(PathClass.fromString(cls), idx + 1) }
                    break
                case 'INSTANCE':
                    builder.useInstanceLabels()
                    break
                case 'MULTICHANNEL':
                    builder.multichannelOutput(true)
                    classifications.eachWithIndex { cls, idx -> builder.addLabel(PathClass.fromString(cls), idx + 1) }
                    break
            }
    
            labelServer = builder.build()
    
            def request = RegionRequest.createInstance(
                    labelServer.getPath(), downsample,
                    0, 0, labelServer.getWidth(), labelServer.getHeight())
            def maskImage = labelServer.readRegion(request)
    
            def sanitized = entryName.replaceAll('[^a-zA-Z0-9._\\-]', '_')
            def outputPath = new File(outDir, sanitized[0..-5] + '.' + outputFormat).getAbsolutePath()
            ImageWriterTools.writeImage(maskImage, outputPath)
            println "  OK: ${outputPath}"
            succeeded++
    
            labelServer.close()
            labelServer = null
            imageData.getServer().close()
    
        } catch (Exception e) {
            println "  FAIL: ${e.getMessage()}"
            failed++
            if (labelServer != null) {
                try { labelServer.close() } catch (Exception ignored) {}
        }
    }
}
}

println ''
println "Export complete: ${succeeded} succeeded, ${failed} failed"
